
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jesse Rine Romero
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    private String currentUserName;

    private String currentUserRole;

    public Home(String role, String names) {
        initComponents();
        setLocationRelativeTo(null);
        currentUserName = names;
        currentUserRole = role;  // Store the passed role in currentUserRole
        manageCategory = new ManageCategory(currentUserRole, currentUserName);
        if (!role.equals("Admin")) {  // Check if the role is not "Admin"
            btnuser.setEnabled(false);  // Disable User button
            btnproduct.setEnabled(false);  // Disable Product button
        } else {
            btnuser.setEnabled(true);  // Enable User button
            btnproduct.setEnabled(true);  // Enable Product button
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnuser = new javax.swing.JButton();
        btnproduct = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JButton();
        BG2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(630, 295));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnuser.setBackground(new java.awt.Color(98, 128, 58));
        btnuser.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Users.png"))); // NOI18N
        btnuser.setText("USER");
        btnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserActionPerformed(evt);
            }
        });
        getContentPane().add(btnuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, -1));

        btnproduct.setBackground(new java.awt.Color(98, 128, 58));
        btnproduct.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/product.png"))); // NOI18N
        btnproduct.setText("PRODUCT");
        btnproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 170, -1));

        jPanel2.setBackground(new java.awt.Color(242, 239, 238));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/kjhgfd-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(123, 164, 68));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 20, 20));

        jPanel5.setBackground(new java.awt.Color(123, 164, 68));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        jPanel7.setBackground(new java.awt.Color(41, 88, 82));
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 20, 20));

        jPanel6.setBackground(new java.awt.Color(41, 88, 82));
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 20, 20));

        btnlogout.setBackground(new java.awt.Color(98, 128, 58));
        btnlogout.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Exit.png"))); // NOI18N
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 280));

        BG2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/home.png"))); // NOI18N
        BG2.setName(""); // NOI18N
        getContentPane().add(BG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 280));

        jPanel3.setBackground(new java.awt.Color(123, 164, 68));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 110));

        jPanel1.setBackground(new java.awt.Color(41, 88, 82));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 630, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserActionPerformed
        // TODO add your handling code here:
        new ManageUser(currentUserRole, currentUserName).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnuserActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close the app?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnlogoutActionPerformed
    private ManageOrder manageOrder;  // Declare ManageOrder reference at the top of Home class
    private ManageCategory manageCategory;
    private void btnproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductActionPerformed
        // TODO add your handling code here:
        if (manageOrder == null) {
            manageOrder = new ManageOrder(currentUserRole, currentUserName);  // Initialize ManageOrder if not already done
        }
        new ManageProduct(currentUserRole, currentUserName).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnproductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG2;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnproduct;
    private javax.swing.JButton btnuser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
