
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jesse Rine Romero
 */
public class Login extends javax.swing.JFrame {

    private int temp;
    private static final int MAX_LOGIN_ATTEMPTS = 5;
    private int loginAttempts = 0;
    private boolean isLocked = false;
    private Timer lockTimer;

    private void handleFailedLogin() {
        loginAttempts++;
        if (loginAttempts >= MAX_LOGIN_ATTEMPTS) {
            isLocked = true;
            LOGIN.setEnabled(false);

            // Start the lock timer
            lockTimer = new Timer(30000, (e) -> {
                isLocked = false;
                loginAttempts = 0;
                LOGIN.setEnabled(true);

                // Stop the timer after execution
                ((Timer) e.getSource()).stop();
            });
            lockTimer.setRepeats(false); // Ensure the timer executes only once
            lockTimer.start();

            JOptionPane.showMessageDialog(this, "Account temporarily locked. Please wait 30 seconds.");
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect credentials. Attempts remaining: "
                    + (MAX_LOGIN_ATTEMPTS - loginAttempts));
        }
    }

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        LOGIN = new javax.swing.JButton();
        CLOSE = new javax.swing.JButton();
        spass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 450));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(254, 254, 254));
        jPanel5.setToolTipText("");
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/logingg.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 500, -1));

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 88, 82));
        jLabel2.setText("USERNAME:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, 20));

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 88, 82));
        jLabel3.setText("PASSWORD:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 20));

        txtemail.setBackground(new java.awt.Color(254, 254, 254));
        txtemail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 113, 48), 2, true));
        jPanel5.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 420, 40));

        txtpassword.setBackground(new java.awt.Color(254, 254, 254));
        txtpassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 113, 48), 2, true));
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        jPanel5.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 420, 40));

        LOGIN.setBackground(new java.awt.Color(98, 128, 58));
        LOGIN.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        LOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/btnlogin.png"))); // NOI18N
        LOGIN.setText("LOGIN");
        LOGIN.setBorder(null);
        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });
        jPanel5.add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 118, 40));

        CLOSE.setBackground(new java.awt.Color(98, 128, 58));
        CLOSE.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/btnclose (1).png"))); // NOI18N
        CLOSE.setText("CLOSE");
        CLOSE.setBorder(null);
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });
        jPanel5.add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 118, 40));

        spass.setText("Show Password");
        spass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spassActionPerformed(evt);
            }
        });
        jPanel5.add(spass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 30));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 88, 82));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log In");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 460, 90));

        jPanel8.setBackground(new java.awt.Color(41, 88, 82));
        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 20, 20));

        jPanel9.setBackground(new java.awt.Color(41, 88, 82));
        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        jPanel10.setBackground(new java.awt.Color(123, 164, 68));
        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 20, 20));

        jPanel11.setBackground(new java.awt.Color(123, 164, 68));
        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 20, 20));

        jPanel12.setBackground(new java.awt.Color(41, 88, 82));
        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 10, 10));

        jPanel13.setBackground(new java.awt.Color(41, 88, 82));
        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 10, 10));

        jPanel15.setBackground(new java.awt.Color(41, 88, 82));
        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel16.setBackground(new java.awt.Color(41, 88, 82));
        jPanel5.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 10));

        jPanel14.setBackground(new java.awt.Color(123, 164, 68));
        jPanel5.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 10, 10));

        jPanel17.setBackground(new java.awt.Color(123, 164, 68));
        jPanel5.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 10, 10));

        jPanel18.setBackground(new java.awt.Color(123, 164, 68));
        jPanel5.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 10, 10));

        jPanel19.setBackground(new java.awt.Color(123, 164, 68));
        jPanel5.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 10, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 500, 410));

        jPanel1.setBackground(new java.awt.Color(41, 88, 82));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 100));

        jPanel3.setBackground(new java.awt.Color(123, 164, 68));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 50, 360));

        jPanel2.setBackground(new java.awt.Color(123, 164, 68));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 50, 360));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 540, 10));

        jPanel4.setBackground(new java.awt.Color(123, 164, 68));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 540, 40));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 450));

        BG.setBackground(new java.awt.Color(255, 255, 204));
        BG.setForeground(new java.awt.Color(255, 255, 204));
        BG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/c6df8c71-7d64-4e31-ae86-89df59ca7b6d.jpeg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close this application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_CLOSEActionPerformed

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
       if (isLocked) {
            JOptionPane.showMessageDialog(this, "Account is temporarily locked. Please wait.");
            return;
        }

        String el = txtemail.getText();
        String initial = new String(txtpassword.getPassword()); // Correctly convert char[] to String

        try {
            String hashedPassword = PasswordHashing.hashPassword(initial);

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");
            ps = con.prepareStatement("SELECT userrole, name FROM inventorymanagementsystem WHERE username = ? AND password = ?");
            ps.setString(1, el);
            ps.setString(2, hashedPassword);
            rs = ps.executeQuery();

            temp = 0;
            while (rs.next()) {
                temp = 1;
                String userName = rs.getString("name");
                String userRole = rs.getString("userrole");
                setVisible(false);
                new Home(userRole, userName).setVisible(true);
            }
            if (temp == 0) {
                handleFailedLogin(); // Call the updated method here
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_LOGINActionPerformed

    private void spassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spassActionPerformed
       if (spass.isSelected()) {
            txtpassword.setEchoChar((char) 0);
        } else {
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_spassActionPerformed

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
                                    
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        LOGINActionPerformed(new java.awt.event.ActionEvent(evt.getSource(), evt.getID(), "EnterPressed"));
    }


    }//GEN-LAST:event_txtpasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton CLOSE;
    private javax.swing.JButton LOGIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JCheckBox spass;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
