
import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ACLC PC17
 */
public class ManageProduct extends javax.swing.JFrame {

    private int productPk = 0;
    private String currentUserRole;
    private String currentUserName;
    private ManageOrder manageOrder;
    /**
     * Creates new form ManageProduct
     */
    public ManageProduct(ManageOrder order) {
    this.manageOrder = order;
    initComponents();
    refresh();
}

    public ManageProduct() {
        
        initComponents();
        String role = null;
        setLocationRelativeTo(null);
        currentUserRole = role;
        this.currentUserRole = role;
        refresh();
       

        DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();
        tableProduct.setModel(new DefaultTableModel(model.getDataVector(), getColumnNames(model)) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;  // Disable editing for all cells
            }
        });
    }

    private Vector<String> getColumnNames(DefaultTableModel model) {
        Vector<String> columnNames = new Vector<>();
        for (int i = 0; i < model.getColumnCount(); i++) {
            columnNames.add(model.getColumnName(i));
        }
        return columnNames;
    }

    private void refresh() {
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();
        model.setRowCount(0);

        try {
            // Establish database connection
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");

            // Execute the query to get all products
            String query = "SELECT * FROM product";
            ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            // Loop through the result set and add each product to the table
            while (rs.next()) {
                String id = rs.getString("id");
                String name = rs.getString("name");
                String quantity = rs.getString("quantity");
                String price = rs.getString("price");
                String description = rs.getString("description");
                String category = rs.getString("category");

                // Add row to the table
                model.addRow(new Object[]{id, name, quantity, price, description, category});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Failed to refresh product list: " + e.getMessage());
        }
    }

    public ManageProduct(String role, String names) {
        initComponents();
        setLocationRelativeTo(null);
        this.currentUserRole = role;
        this.currentUserName = names;
        currentUserRole = role;  // Set the role
        refresh();  // Refresh data when the form is initialized
    }

    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel m;



    private void formComponentShown(java.awt.event.ComponentEvent evt) {

        DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();

        try {
//          Connection con = ConnectionProvider.getCon();
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");
            ps = con.prepareStatement("Select * from category where userrole = ?");
            ps.executeQuery("Select * from category");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("category_pk"), rs.getString("name")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        update.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BG5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 520));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(163, 198, 134));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 950, 10);

        jPanel8.setBackground(new java.awt.Color(41, 88, 82));
        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 510, 950, 10);

        jPanel2.setBackground(new java.awt.Color(41, 88, 82));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE PRODUCT:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 5, -1, 70));

        jPanel4.setBackground(new java.awt.Color(163, 198, 134));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 20, 20));

        jPanel5.setBackground(new java.awt.Color(163, 198, 134));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 60, 20, 10));

        jPanel6.setBackground(new java.awt.Color(163, 198, 134));
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 20, -1));

        jPanel7.setBackground(new java.awt.Color(163, 198, 134));
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 950, 70);

        save.setBackground(new java.awt.Color(0, 29, 29));
        save.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("ADD/EDIT PRODUCT");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(30, 450, 160, 40);

        update.setBackground(new java.awt.Color(0, 29, 29));
        update.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("ADD/EDIT CATEGORY");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(200, 450, 160, 40);

        delete.setBackground(new java.awt.Color(0, 29, 29));
        delete.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(370, 450, 160, 40);

        close.setBackground(new java.awt.Color(0, 29, 29));
        close.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(540, 450, 160, 40);

        tableProduct.setBackground(new java.awt.Color(254, 254, 254));
        tableProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tableProduct.setForeground(new java.awt.Color(41, 88, 82));
        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "Price", "Description", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProduct.setToolTipText("");
        tableProduct.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableProduct);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 130, 890, 310);

        jLabel7.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/magnifying-glass.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 90, 30, 30);

        searchbar.setBackground(new java.awt.Color(254, 254, 254));
        searchbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 88, 82), 2, true));
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        searchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchbarKeyTyped(evt);
            }
        });
        getContentPane().add(searchbar);
        searchbar.setBounds(60, 90, 860, 30);

        jPanel1.setBackground(new java.awt.Color(163, 198, 134));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 520);

        BG5.setBackground(new java.awt.Color(153, 153, 153));
        BG5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/MO.png"))); // NOI18N
        getContentPane().add(BG5);
        BG5.setBounds(0, 0, 1172, 796);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
         // TODO add your handling code here:
        if (manageOrder == null) {
            manageOrder = new ManageOrder(currentUserRole, currentUserName);  // Initialize ManageOrder if not already done
        }
        new ManageProduct1(currentUserRole, currentUserName).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_saveActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         // TODO add your handling code here:
        if (manageOrder == null) {
            manageOrder = new ManageOrder(currentUserRole, currentUserName);  // Initialize ManageOrder if not already done
        }
        new ManageCategory(currentUserRole, currentUserName).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateActionPerformed

    // Method to clear the text fields
  
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        /*DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();
        model.setRowCount(0);
        
        try {
        // Establish database connection
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");
        
        // Execute the query to get all products
        String query = "SELECT * FROM product";
        ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        
        // Loop through the result set and add each product to the table
        while (rs.next()) {
        String id = rs.getString("id");
        String name = rs.getString("name");
        String quantity = rs.getString("quantity");
        String price = rs.getString("price");
        String description = rs.getString("description");
        String category = rs.getString("category");
        
        // Add row to the table
        model.addRow(new Object[]{id, name, quantity, price, description, category});
        }
        
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Failed to refresh product list: " + e.getMessage());
        }*/
        int selectedRow = tableProduct.getSelectedRow(); // Get the selected row index
        if (selectedRow == -1) {
            // No row is selected
            JOptionPane.showMessageDialog(this, "Please select a product to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirm deletion
        int confirmation = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete the selected product?",
                "Delete Confirmation", JOptionPane.YES_NO_OPTION);

        if (confirmation == JOptionPane.YES_OPTION) {
            try {
                // Get the product ID from the selected row
                String productId = tableProduct.getValueAt(selectedRow, 0).toString();
                System.out.println("Product ID to delete: " + productId); // Debug message

                // Connect to the database
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");

                // Execute DELETE SQL query
                String deleteQuery = "DELETE FROM product WHERE id = ?";
                PreparedStatement ps = con.prepareStatement(deleteQuery);

                // Pass the ID as appropriate (string or integer)
                ps.setString(1, productId); // If id is VARCHAR
                // ps.setInt(1, Integer.parseInt(productId)); // Uncomment if id is INT

                int rowsDeleted = ps.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(this, "Product deleted successfully.");

                    // Remove the row from the table model
                    DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();
                    model.removeRow(selectedRow);

                    // Clear the text fields
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete product.", "Error", JOptionPane.ERROR_MESSAGE);
                }

                ps.close();
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error deleting product: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace(); // Debug the error
            }
        }
    }//GEN-LAST:event_deleteActionPerformed


    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close the app?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            this.dispose();
            if (currentUserRole != null) {
                new Home(currentUserRole, currentUserName).setVisible(true);
            } else {
// Handle the case where currentUserRole is null (e.g., show an error message)
                JOptionPane.showMessageDialog(this, "Error: User  role is not defined.");
            }
        }
    }//GEN-LAST:event_closeActionPerformed

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();
        model.setRowCount(0);

      
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");

            // Query to fetch products based on the selected category
            String query;
            

            ResultSet rs = ps.executeQuery();

            // Loop through the result set and add each product to the table
            while (rs.next()) {
                String id = rs.getString("id");
                String name = rs.getString("name");
                String quantity = rs.getString("quantity");
                String price = rs.getString("price");
                String description = rs.getString("description");
                String category = rs.getString("category");

                // Add row to the table
                model.addRow(new Object[]{id, name, quantity, price, description, category});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Failed to search products: " + e.getMessage());
        }

    }//GEN-LAST:event_searchbarActionPerformed

    private void searchbarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbarKeyTyped
        // TODO add your handling code here:
        if (searchbar.getText().length() >= 30) {
            evt.consume();
            return;
        }
        try {
            // Mysql Connector
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");
            String query = "SELECT * FROM product WHERE id LIKE ? OR name LIKE ? OR quantity LIKE ? OR price LIKE ? "
                    + "OR description LIKE ? OR category LIKE ?";

            ps = con.prepareStatement(query);
            String searchText = "%" + searchbar.getText() + "%";

            ps.setString(1, searchText);
            ps.setString(2, searchText);
            ps.setString(3, searchText);
            ps.setString(4, searchText);
            ps.setString(5, searchText);
            ps.setString(6, searchText);

            rs = ps.executeQuery();
            DefaultTableModel dt = (DefaultTableModel) tableProduct.getModel();
            dt.setRowCount(0);

            while (rs.next()) {
                dt.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)
                });
            }

        } catch (SQLException ex) {
            Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_searchbarKeyTyped

    private void tableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) { // Single click
            int selectedRow = tableProduct.getSelectedRow();
            if (selectedRow != -1) {
                // Get data from the selected row
                String id = tableProduct.getValueAt(selectedRow, 0).toString(); // ID column
                String names = tableProduct.getValueAt(selectedRow, 1).toString(); // Name column
                String quantity = tableProduct.getValueAt(selectedRow, 2).toString(); // Quantity column
                String prices = tableProduct.getValueAt(selectedRow, 3).toString(); // Price column
                String decsription = tableProduct.getValueAt(selectedRow, 4).toString(); // Decsription column
                String categorys = tableProduct.getValueAt(selectedRow, 5).toString(); // Category column

                // Retrieve password and role from the database
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");

                    // Query to fetch password and role based on ID
                    String query = "SELECT password, userrole FROM inventorymanagementsystem WHERE appuser_pk = ?";
                    ps = con.prepareStatement(query);
                    ps.setString(1, id);
                    rs = ps.executeQuery();

                } catch (ClassNotFoundException | SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error fetching user details: " + e.getMessage());
                }


            }
        }
    }//GEN-LAST:event_tableProductMouseClicked

    private void searchbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbarKeyReleased
        // TODO add your handling code here:
        try {
            // Mysql Connector
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement", "root", "");
            String query = "SELECT * FROM product WHERE id LIKE ? OR name LIKE ? OR quantity LIKE ? OR price LIKE ? "
                    + "OR description LIKE ? OR category LIKE ?";

            ps = con.prepareStatement(query);
            String searchText = "%" + searchbar.getText() + "%";

            ps.setString(1, searchText);
            ps.setString(2, searchText);
            ps.setString(3, searchText);
            ps.setString(4, searchText);
            ps.setString(5, searchText);
            ps.setString(6, searchText);

            rs = ps.executeQuery();
            DefaultTableModel dt = (DefaultTableModel) tableProduct.getModel();
            dt.setRowCount(0);

            while (rs.next()) {
                dt.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)
                });
            }

        } catch (SQLException ex) {
            Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchbarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG5;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton save;
    private javax.swing.JTextField searchbar;
    private javax.swing.JTable tableProduct;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
